# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'IMDB_Thing.ui'
#
# Created: Thu Jan  2 22:56:51 2014
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(687, 662)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.lEdit_movieName = QtGui.QLineEdit(self.centralwidget)
        self.lEdit_movieName.setObjectName(_fromUtf8("lEdit_movieName"))
        self.horizontalLayout.addWidget(self.lEdit_movieName)
        self.CBoxYear = QtGui.QComboBox(self.centralwidget)
        self.CBoxYear.setFocusPolicy(QtCore.Qt.TabFocus)
        self.CBoxYear.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.CBoxYear.setMaxCount(1000)
        self.CBoxYear.setInsertPolicy(QtGui.QComboBox.InsertAtBottom)
        self.CBoxYear.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToContentsOnFirstShow)
        self.CBoxYear.setFrame(True)
        self.CBoxYear.setObjectName(_fromUtf8("CBoxYear"))
        self.horizontalLayout.addWidget(self.CBoxYear)
        self.bt_go = QtGui.QPushButton(self.centralwidget)
        self.bt_go.setObjectName(_fromUtf8("bt_go"))
        self.horizontalLayout.addWidget(self.bt_go)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.lb_title = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook L"))
        font.setPointSize(24)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.lb_title.setFont(font)
        self.lb_title.setStyleSheet(_fromUtf8("color: rgb(0, 85, 0);\n"
"font: 75 24pt \"Century Schoolbook L\";"))
        self.lb_title.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_title.setObjectName(_fromUtf8("lb_title"))
        self.verticalLayout.addWidget(self.lb_title)
        self.scrollArea = QtGui.QScrollArea(self.centralwidget)
        self.scrollArea.setMinimumSize(QtCore.QSize(400, 280))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 418, 298))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.groupBox = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(400, 280))
        self.groupBox.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.groupBox.setTitle(_fromUtf8(""))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.lb_type = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Serif"))
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lb_type.setFont(font)
        self.lb_type.setStyleSheet(_fromUtf8("font: 13pt \"Serif\";\n"
"color: rgb(100, 100, 100);"))
        self.lb_type.setObjectName(_fromUtf8("lb_type"))
        self.gridLayout.addWidget(self.lb_type, 7, 1, 1, 1)
        self.left_year = QtGui.QLabel(self.groupBox)
        self.left_year.setStyleSheet(_fromUtf8("font: 13pt \"Serif\";\n"
"color: rgb(100, 100, 100);"))
        self.left_year.setObjectName(_fromUtf8("left_year"))
        self.gridLayout.addWidget(self.left_year, 1, 0, 1, 1)
        self.year = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.year.sizePolicy().hasHeightForWidth())
        self.year.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Serif"))
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.year.setFont(font)
        self.year.setStyleSheet(_fromUtf8("font: 13pt \"Serif\";\n"
"color: rgb(100, 100, 100);"))
        self.year.setObjectName(_fromUtf8("year"))
        self.gridLayout.addWidget(self.year, 1, 1, 1, 1)
        self.left_genre = QtGui.QLabel(self.groupBox)
        self.left_genre.setStyleSheet(_fromUtf8("font: 13pt \"Serif\";\n"
"color: rgb(100, 100, 100);"))
        self.left_genre.setObjectName(_fromUtf8("left_genre"))
        self.gridLayout.addWidget(self.left_genre, 2, 0, 1, 1)
        self.genre = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.genre.sizePolicy().hasHeightForWidth())
        self.genre.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Serif"))
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.genre.setFont(font)
        self.genre.setStyleSheet(_fromUtf8("font: 13pt \"Serif\";\n"
"color: rgb(100, 100, 100);"))
        self.genre.setObjectName(_fromUtf8("genre"))
        self.gridLayout.addWidget(self.genre, 2, 1, 1, 1)
        self.left_runtime = QtGui.QLabel(self.groupBox)
        self.left_runtime.setStyleSheet(_fromUtf8("font: 13pt \"Serif\";\n"
"color: rgb(100, 100, 100);"))
        self.left_runtime.setObjectName(_fromUtf8("left_runtime"))
        self.gridLayout.addWidget(self.left_runtime, 3, 0, 1, 1)
        self.runtime = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.runtime.sizePolicy().hasHeightForWidth())
        self.runtime.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Serif"))
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.runtime.setFont(font)
        self.runtime.setStyleSheet(_fromUtf8("font: 13pt \"Serif\";\n"
"color: rgb(100, 100, 100);"))
        self.runtime.setObjectName(_fromUtf8("runtime"))
        self.gridLayout.addWidget(self.runtime, 3, 1, 1, 1)
        self.left_actors = QtGui.QLabel(self.groupBox)
        self.left_actors.setStyleSheet(_fromUtf8("font: 13pt \"Serif\";\n"
"color: rgb(100, 100, 100);"))
        self.left_actors.setObjectName(_fromUtf8("left_actors"))
        self.gridLayout.addWidget(self.left_actors, 4, 0, 1, 1)
        self.actors = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Serif"))
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.actors.setFont(font)
        self.actors.setStyleSheet(_fromUtf8("font: 13pt \"Serif\";\n"
"color: rgb(100, 100, 100);"))
        self.actors.setObjectName(_fromUtf8("actors"))
        self.gridLayout.addWidget(self.actors, 4, 1, 1, 1)
        self.left_director = QtGui.QLabel(self.groupBox)
        self.left_director.setStyleSheet(_fromUtf8("font: 13pt \"Serif\";\n"
"color: rgb(100, 100, 100);"))
        self.left_director.setObjectName(_fromUtf8("left_director"))
        self.gridLayout.addWidget(self.left_director, 5, 0, 1, 1)
        self.director = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Serif"))
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.director.setFont(font)
        self.director.setStyleSheet(_fromUtf8("font: 13pt \"Serif\";\n"
"color: rgb(100, 100, 100);"))
        self.director.setObjectName(_fromUtf8("director"))
        self.gridLayout.addWidget(self.director, 5, 1, 1, 1)
        self.left_awards = QtGui.QLabel(self.groupBox)
        self.left_awards.setStyleSheet(_fromUtf8("font: 13pt \"Serif\";\n"
"color: rgb(100, 100, 100);"))
        self.left_awards.setObjectName(_fromUtf8("left_awards"))
        self.gridLayout.addWidget(self.left_awards, 6, 0, 1, 1)
        self.awards = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Serif"))
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.awards.setFont(font)
        self.awards.setStyleSheet(_fromUtf8("font: 13pt \"Serif\";\n"
"color: rgb(100, 100, 100);"))
        self.awards.setObjectName(_fromUtf8("awards"))
        self.gridLayout.addWidget(self.awards, 6, 1, 1, 1)
        self.left_lb_type = QtGui.QLabel(self.groupBox)
        self.left_lb_type.setStyleSheet(_fromUtf8("font: 13pt \"Serif\";\n"
"color: rgb(100, 100, 100);"))
        self.left_lb_type.setObjectName(_fromUtf8("left_lb_type"))
        self.gridLayout.addWidget(self.left_lb_type, 7, 0, 1, 1)
        self.left_country = QtGui.QLabel(self.groupBox)
        self.left_country.setStyleSheet(_fromUtf8("font: 13pt \"Serif\";\n"
"color: rgb(100, 100, 100);"))
        self.left_country.setObjectName(_fromUtf8("left_country"))
        self.gridLayout.addWidget(self.left_country, 8, 0, 1, 1)
        self.country = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Serif"))
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.country.setFont(font)
        self.country.setStyleSheet(_fromUtf8("font: 13pt \"Serif\";\n"
"color: rgb(100, 100, 100);"))
        self.country.setObjectName(_fromUtf8("country"))
        self.gridLayout.addWidget(self.country, 8, 1, 1, 1)
        self.left_language = QtGui.QLabel(self.groupBox)
        self.left_language.setStyleSheet(_fromUtf8("font: 13pt \"Serif\";\n"
"color: rgb(100, 100, 100);"))
        self.left_language.setObjectName(_fromUtf8("left_language"))
        self.gridLayout.addWidget(self.left_language, 9, 0, 1, 1)
        self.language = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Serif"))
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.language.setFont(font)
        self.language.setStyleSheet(_fromUtf8("font: 13pt \"Serif\";\n"
"color: rgb(100, 100, 100);"))
        self.language.setObjectName(_fromUtf8("language"))
        self.gridLayout.addWidget(self.language, 9, 1, 1, 1)
        self.verticalLayout_5.addWidget(self.groupBox)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.plot = QtGui.QTextBrowser(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plot.sizePolicy().hasHeightForWidth())
        self.plot.setSizePolicy(sizePolicy)
        self.plot.setMinimumSize(QtCore.QSize(0, 50))
        self.plot.setMaximumSize(QtCore.QSize(16777215, 200))
        self.plot.setSizeIncrement(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Serif"))
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.plot.setFont(font)
        self.plot.setAutoFillBackground(False)
        self.plot.setStyleSheet(_fromUtf8("background-color: rgb(254, 255, 231);\n"
"color: rgb(107, 107, 107);"))
        self.plot.setFrameShape(QtGui.QFrame.Box)
        self.plot.setObjectName(_fromUtf8("plot"))
        self.verticalLayout.addWidget(self.plot)
        self.votes = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook L"))
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.votes.setFont(font)
        self.votes.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.votes.setAutoFillBackground(False)
        self.votes.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.votes.setObjectName(_fromUtf8("votes"))
        self.verticalLayout.addWidget(self.votes)
        self.goToWebsite = QtGui.QPushButton(self.centralwidget)
        self.goToWebsite.setObjectName(_fromUtf8("goToWebsite"))
        self.verticalLayout.addWidget(self.goToWebsite)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.horizontalLayout_4.addLayout(self.verticalLayout_3)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.lb_rating = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lb_rating.sizePolicy().hasHeightForWidth())
        self.lb_rating.setSizePolicy(sizePolicy)
        self.lb_rating.setMinimumSize(QtCore.QSize(100, 100))
        self.lb_rating.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Serif"))
        font.setPointSize(45)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lb_rating.setFont(font)
        self.lb_rating.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lb_rating.setStyleSheet(_fromUtf8("border-color: rgb(145, 145, 145);\n"
"background-color: rgb(221, 221, 221);\n"
""))
        self.lb_rating.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lb_rating.setFrameShadow(QtGui.QFrame.Plain)
        self.lb_rating.setLineWidth(5)
        self.lb_rating.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_rating.setObjectName(_fromUtf8("lb_rating"))
        self.horizontalLayout_2.addWidget(self.lb_rating)
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.horizontalLayout_2.addWidget(self.line)
        self.lb_rated = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lb_rated.sizePolicy().hasHeightForWidth())
        self.lb_rated.setSizePolicy(sizePolicy)
        self.lb_rated.setMinimumSize(QtCore.QSize(150, 100))
        self.lb_rated.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Serif"))
        font.setPointSize(28)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lb_rated.setFont(font)
        self.lb_rated.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lb_rated.setStyleSheet(_fromUtf8("border-color: rgb(145, 145, 145);\n"
"background-color: rgb(188, 188, 188);"))
        self.lb_rated.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lb_rated.setFrameShadow(QtGui.QFrame.Plain)
        self.lb_rated.setLineWidth(5)
        self.lb_rated.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_rated.setObjectName(_fromUtf8("lb_rated"))
        self.horizontalLayout_2.addWidget(self.lb_rated)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.gfxView_poster = QtGui.QGraphicsView(self.centralwidget)
        brush = QtGui.QBrush(QtGui.QColor(102, 97, 95))
        brush.setStyle(QtCore.Qt.Dense2Pattern)
        self.gfxView_poster.setBackgroundBrush(brush)
        self.gfxView_poster.setObjectName(_fromUtf8("gfxView_poster"))
        self.verticalLayout_2.addWidget(self.gfxView_poster)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 687, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menu_File = QtGui.QMenu(self.menubar)
        self.menu_File.setObjectName(_fromUtf8("menu_File"))
        self.menu_About = QtGui.QMenu(self.menubar)
        self.menu_About.setObjectName(_fromUtf8("menu_About"))
        self.menu_About_2 = QtGui.QMenu(self.menubar)
        self.menu_About_2.setObjectName(_fromUtf8("menu_About_2"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.action_Save = QtGui.QAction(MainWindow)
        self.action_Save.setObjectName(_fromUtf8("action_Save"))
        self.actionSave_as_html = QtGui.QAction(MainWindow)
        self.actionSave_as_html.setObjectName(_fromUtf8("actionSave_as_html"))
        self.action_Load = QtGui.QAction(MainWindow)
        self.action_Load.setObjectName(_fromUtf8("action_Load"))
        self.action_Exit = QtGui.QAction(MainWindow)
        self.action_Exit.setObjectName(_fromUtf8("action_Exit"))
        self.menu_File.addAction(self.action_Save)
        self.menu_File.addAction(self.actionSave_as_html)
        self.menu_File.addAction(self.action_Load)
        self.menu_File.addAction(self.action_Exit)
        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menu_About.menuAction())
        self.menubar.addAction(self.menu_About_2.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.lEdit_movieName, self.CBoxYear)
        MainWindow.setTabOrder(self.CBoxYear, self.bt_go)
        MainWindow.setTabOrder(self.bt_go, self.goToWebsite)
        MainWindow.setTabOrder(self.goToWebsite, self.gfxView_poster)
        MainWindow.setTabOrder(self.gfxView_poster, self.plot)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.bt_go.setText(QtGui.QApplication.translate("MainWindow", "Go", None, QtGui.QApplication.UnicodeUTF8))
        self.lb_title.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p align=\"center\">TextLabel</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.lb_type.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.left_year.setText(QtGui.QApplication.translate("MainWindow", "Year:", None, QtGui.QApplication.UnicodeUTF8))
        self.year.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.left_genre.setText(QtGui.QApplication.translate("MainWindow", "Genre:", None, QtGui.QApplication.UnicodeUTF8))
        self.genre.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.left_runtime.setText(QtGui.QApplication.translate("MainWindow", "Runtime:", None, QtGui.QApplication.UnicodeUTF8))
        self.runtime.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.left_actors.setText(QtGui.QApplication.translate("MainWindow", "Starring", None, QtGui.QApplication.UnicodeUTF8))
        self.actors.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.left_director.setText(QtGui.QApplication.translate("MainWindow", "Directed by ", None, QtGui.QApplication.UnicodeUTF8))
        self.director.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.left_awards.setText(QtGui.QApplication.translate("MainWindow", "Awards:", None, QtGui.QApplication.UnicodeUTF8))
        self.awards.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.left_lb_type.setText(QtGui.QApplication.translate("MainWindow", "Movie/Series", None, QtGui.QApplication.UnicodeUTF8))
        self.left_country.setText(QtGui.QApplication.translate("MainWindow", "Country", None, QtGui.QApplication.UnicodeUTF8))
        self.country.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.left_language.setText(QtGui.QApplication.translate("MainWindow", "Language", None, QtGui.QApplication.UnicodeUTF8))
        self.language.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.votes.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:400;\">TextLabel</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.goToWebsite.setText(QtGui.QApplication.translate("MainWindow", "Take me to website", None, QtGui.QApplication.UnicodeUTF8))
        self.lb_rating.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">RATED</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.lb_rated.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">RATED</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_File.setTitle(QtGui.QApplication.translate("MainWindow", "&File", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_About.setTitle(QtGui.QApplication.translate("MainWindow", "&Preferences", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_About_2.setTitle(QtGui.QApplication.translate("MainWindow", "&About", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Save.setText(QtGui.QApplication.translate("MainWindow", "&Save as pdf", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_as_html.setText(QtGui.QApplication.translate("MainWindow", "Save as &html", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Load.setText(QtGui.QApplication.translate("MainWindow", "&Load file", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Exit.setText(QtGui.QApplication.translate("MainWindow", "&Exit", None, QtGui.QApplication.UnicodeUTF8))

